title: Mat√≠as Cajarabilla
description: ""
baseurl: ""
url: "https://matiascajarabilla.github.io"
theme: minima
plugins:
  - jekyll-feed
  - jekyll-seo-tag

# author: Tu Nombre
# email: tu@email.com

linkedin_username: linkedin.com/in/matiascajarabilla
github_username:  github.com/matiascajarabilla

# Formato de fecha
date_format: "%d-%m-%Y"

# Opcional: Mostrar extractos de posts en la home
show_excerpts: true

header_pages:
#  - index.md
  - bookmarks.md
#  - proyectos.md
  - cv.md

#collections:
#  proyectos:
#    output: true
#    permalink: /proyectos/:path/

collections:
  bookmarks:
    output: true
    permalink: /bookmarks/:path/
