# title: Matías Cajarabilla
description: >- # El " >- " permite escribir en varias líneas
  Portafolio profesional de Matías Cajarabilla. 
  Proyectos, CV y recursos.
theme: minima # Es el tema más simple y limpio por defecto
plugins:
  - jekyll-seo-tag

nav_pages:
  - index.md
  - cv.md
  - proyectos.md

# definimos 'proyectos' como una colección
collections:
  proyectos:
    output: true
    permalink: /proyectos/:path/

minima:
  social_links:
    - { platform: github, user_url: "https://github.com/matiascajarabilla" }
    - { platform: linkedin, user_url: "https://linkedin.com/in/matiascajarabilla" }