# title: Matías Cajarabilla
theme: minima # Es el tema más simple y limpio por defecto
plugins:
  - jekyll-seo-tag

nav_pages:
  - index.md
  - cv.md
  - proyectos.md

# definimos 'proyectos' como una colección
collections:
  proyectos:
    output: true
    permalink: /proyectos/:path/