title: Matias Cajarabilla
description: ""
baseurl: ""
url: "https://matiascajarabilla.github.io"
theme: minima
plugins:
  - jekyll-feed
  - jekyll-seo-tag

author: Tu Nombre
email: tu@email.com

# En Minima 2.5, las redes se ponen como variables directas, NO como lista
github_username:  tu-usuario-github
twitter_username: tu-usuario-twitter
linkedin_username: tu-usuario-linkedin

# Formato de fecha
date_format: "%d-%m-%Y"

# Opcional: Mostrar extractos de posts en la home
show_excerpts: false

header_pages:
  - index.md
  - proyectos.md
  - cv.md

collections:
  proyectos:
    output: true
    permalink: /proyectos/:path/

