# title: Matías Cajarabilla
theme: minima # Es el tema más simple y limpio por defecto
plugins:
  - jekyll-seo-tag

# definimos 'proyectos' como una colección
collections:
  proyectos:
    output: true
    permalink: /proyectos/:path/